spring:
  datasource:
    url: jdbc:h2:mem:guitardb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      # WARNING: H2 console should NEVER be enabled in production profiles!
      enabled: true
      settings:
        web-allow-others: false
